// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using forms.Database;

namespace formservice.Migrations
{
    [DbContext(typeof(FormsDbContext))]
    partial class FormsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("forms.Database.Models.Field", b =>
                {
                    b.Property<string>("FieldId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Detail")
                        .IsRequired();

                    b.Property<string>("FormId")
                        .IsRequired();

                    b.Property<int>("Index");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("FieldId");

                    b.HasIndex("FormId")
                        .HasName("Index_Field_FormId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("forms.Database.Models.FieldData", b =>
                {
                    b.Property<string>("FieldDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data")
                        .IsRequired();

                    b.Property<string>("FieldId")
                        .IsRequired();

                    b.Property<string>("FormDataId")
                        .IsRequired();

                    b.Property<string>("FormId")
                        .IsRequired();

                    b.HasKey("FieldDataId");

                    b.HasIndex("FormDataId")
                        .HasName("Index_FieldData_FormDataId");

                    b.HasIndex("FormId", "FieldId")
                        .HasName("Index_FieldData_FormId_And_FieldId");

                    b.ToTable("FieldData");
                });

            modelBuilder.Entity("forms.Database.Models.Form", b =>
                {
                    b.Property<string>("FormId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("FieldsCount");

                    b.Property<string>("Header")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Settings")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<string>("Webhook")
                        .IsRequired();

                    b.HasKey("FormId");

                    b.HasIndex("FormId")
                        .IsUnique()
                        .HasName("Index_Form_FormId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("forms.Database.Models.FormData", b =>
                {
                    b.Property<string>("FormDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatedBy")
                        .IsRequired();

                    b.Property<string>("FormId")
                        .IsRequired();

                    b.Property<string>("Ip")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<string>("UpdatedBy")
                        .IsRequired();

                    b.Property<string>("UserAgent")
                        .IsRequired();

                    b.HasKey("FormDataId");

                    b.HasIndex("FormId")
                        .HasName("Index_FormData_FormId");

                    b.ToTable("FormData");
                });

            modelBuilder.Entity("forms.Database.Models.FormDataHistory", b =>
                {
                    b.Property<string>("FormDataHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FieldDataList")
                        .IsRequired();

                    b.Property<string>("FormDataId")
                        .IsRequired();

                    b.Property<string>("Ip")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.Property<string>("UpdatedBy")
                        .IsRequired();

                    b.Property<string>("UserAgent")
                        .IsRequired();

                    b.HasKey("FormDataHistoryId");

                    b.HasIndex("FormDataId")
                        .HasName("Index_FormDataHistory_FormDataId");

                    b.ToTable("FormDataHistories");
                });

            modelBuilder.Entity("forms.Database.Models.FormHistory", b =>
                {
                    b.Property<string>("FormHistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Fields")
                        .IsRequired();

                    b.Property<string>("FormId")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("FormHistoryId");

                    b.HasIndex("FormId")
                        .HasName("Index_FormHistory_FormId");

                    b.ToTable("FormHistories");
                });

            modelBuilder.Entity("forms.Database.Models.Field", b =>
                {
                    b.HasOne("forms.Database.Models.Form", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .HasConstraintName("ForeignKey_Field_Form")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("forms.Database.Models.FieldData", b =>
                {
                    b.HasOne("forms.Database.Models.FormData", "FormData")
                        .WithMany("FieldDataList")
                        .HasForeignKey("FormDataId")
                        .HasConstraintName("ForeignKey_FieldData_FormData")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("forms.Database.Models.FormData", b =>
                {
                    b.HasOne("forms.Database.Models.Form", "Form")
                        .WithMany("FormDataList")
                        .HasForeignKey("FormId")
                        .HasConstraintName("ForeignKey_FormData_Form")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("forms.Database.Models.FormDataHistory", b =>
                {
                    b.HasOne("forms.Database.Models.FormData", "FormData")
                        .WithMany("Histories")
                        .HasForeignKey("FormDataId")
                        .HasConstraintName("ForeignKey_FormDataHistory_FormData")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("forms.Database.Models.FormHistory", b =>
                {
                    b.HasOne("forms.Database.Models.Form", "Form")
                        .WithMany("Histories")
                        .HasForeignKey("FormId")
                        .HasConstraintName("ForeignKey_FormHistory_Form")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
